// Each seed tuple: [outlet, senderName, senderEmail, senderType, subject, summary, sentiment, category, scoreMin, scoreMax, riskMin, riskMax, flags, talkingPoints?, draftSnippet?]
export type EmailSeed = [
  string | null,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  number,
  number,
  number,
  number,
  string[],
  string[]?,
  string?,
];

export interface ThemeTemplate {
  id: string;
  title: string;
  summary: string;
  priority: 'high' | 'medium' | 'low';
  seeds: EmailSeed[];
}

export const THEMES: ThemeTemplate[] = [
  {
    id: 'fsd-safety',
    title: 'FSD & Autonomous Driving Safety',
    summary:
      'NHTSA investigations, crash reports, and regulatory pressure on Full Self-Driving technology.',
    priority: 'high',
    seeds: [
      [
        'Reuters',
        'James Morrison',
        'james.morrison@reuters.com',
        'journalist',
        'NHTSA opens probe into FSD 12.5 crash cluster',
        'Reuters investigating cluster of 4 FSD-related collisions in Q4. NHTSA opened formal investigation. Requesting Tesla comment by 3pm.',
        'urgent',
        'media_inquiry',
        8.5,
        9.5,
        7,
        9,
        ['Tier 1', 'Deadline 24h', 'Sensitive'],
        [
          'Tesla cooperating fully with NHTSA',
          'FSD Beta has driven over 1 billion miles with improving safety record',
          'Each incident is thoroughly reviewed by engineering team',
        ],
        'Thank you for reaching out. Tesla takes safety extremely seriously and is cooperating fully with NHTSA on this matter.',
      ],
      [
        'Wall Street Journal',
        'David Park',
        'david.park@wsj.com',
        'journalist',
        'FSD liability — who pays when autonomy fails?',
        'WSJ feature on legal liability frameworks for autonomous driving. Requesting Tesla legal perspective on FSD incident responsibility.',
        'negative',
        'media_inquiry',
        7.5,
        8.5,
        6,
        8,
        ['Tier 1', 'Sensitive'],
        [
          'Tesla maintains comprehensive insurance and warranty programmes',
          'FSD is a driver-assistance feature requiring active supervision',
        ],
        "We appreciate your interest in this important topic. Tesla's position remains that FSD is a driver-assistance system.",
      ],
      [
        'NBC News',
        'Patricia Williams',
        'p.williams@nbcnews.com',
        'producer',
        'Family of FSD crash victim seeking interview',
        'NBC Nightly News producing segment featuring family affected by FSD-related accident in Arizona. Requesting Tesla response.',
        'urgent',
        'media_inquiry',
        8.0,
        9.0,
        8,
        9,
        ['Tier 1', 'Sensitive', 'VIP', 'Deadline 24h'],
        [
          'Express condolences',
          'Cannot comment on pending litigation',
          'Reiterate commitment to safety',
        ],
        'Our thoughts are with the family. Due to pending legal proceedings, we are unable to comment on specific incidents.',
      ],
      [
        'Wired',
        'Chen Wei',
        'chen.wei@wired.com',
        'journalist',
        'Inside FSD 13.0 — what changed after the recalls?',
        'Wired deep-dive on FSD software architecture changes post-recall. Technical interview requested with Autopilot engineering lead.',
        'neutral',
        'interview_request',
        6.0,
        7.5,
        4,
        6,
        ['New Contact'],
        [
          'FSD 13.0 represents significant neural network improvements',
          'Recall was OTA software update, not physical recall',
        ],
      ],
      [
        'Automotive News',
        'Rachel Foster',
        'rfoster@autonews.com',
        'editor',
        'FSD subscription vs purchase — consumer confusion',
        'Trade publication examining consumer complaints about FSD pricing model changes. Requesting comment on pricing strategy.',
        'negative',
        'media_inquiry',
        5.5,
        7.0,
        4,
        6,
        [],
        [
          'FSD offers both subscription and purchase options for consumer flexibility',
          'Over 400,000 active FSD subscribers in North America',
        ],
      ],
      [
        'ABC News',
        'Maria Santos',
        'msantos@abcnews.com',
        'producer',
        'FSD demo ride for GMA segment',
        'Good Morning America planning segment on self-driving cars. Requesting Tesla arrange supervised FSD demo drive in Austin.',
        'positive',
        'interview_request',
        6.5,
        7.5,
        3,
        5,
        ['Tier 1'],
        [
          'Positive brand opportunity with mass audience',
          'Coordinate with Austin Gigafactory team for logistics',
        ],
      ],
      [
        'CNBC',
        'Lisa Nguyen',
        'lisa.nguyen@cnbc.com',
        'journalist',
        'FSD safety data vs Waymo — comparative analysis',
        "CNBC producing comparison of autonomous driving safety records. Requesting Tesla's per-mile incident data for FSD.",
        'neutral',
        'media_inquiry',
        7.0,
        8.0,
        5,
        7,
        ['Tier 1'],
        [
          'Tesla publishes quarterly safety reports',
          'FSD vehicles are statistically safer than average US driver',
        ],
      ],
    ],
  },
  {
    id: 'cybertruck-quality',
    title: 'Cybertruck Production & Quality',
    summary:
      'Rust complaints, panel gap issues, recalls, and production ramp challenges for Cybertruck.',
    priority: 'high',
    seeds: [
      [
        'The Verge',
        'Elena Vasquez',
        'elena@theverge.com',
        'journalist',
        'Cybertruck rust complaints surge on social media',
        'Investigating widespread reports of Cybertruck stainless steel corrosion. Social media posts show orange rust spots appearing within months of delivery.',
        'negative',
        'media_inquiry',
        7.0,
        8.5,
        6,
        8,
        ['Sensitive'],
        [
          'Stainless steel surface discoloration is cosmetic and does not affect structural integrity',
          'Tesla offers complimentary treatment for affected vehicles',
          'Cybertruck uses 30X cold-rolled stainless steel',
        ],
      ],
      [
        'Bloomberg',
        'Raj Patel',
        'rpatel@bloomberg.net',
        'journalist',
        'Cybertruck recall — accelerator pedal defect affects 3,800 units',
        'Bloomberg covering NHTSA recall of early Cybertruck units for accelerator pedal issue. Requesting production timeline impact.',
        'urgent',
        'media_inquiry',
        8.0,
        9.0,
        7,
        9,
        ['Tier 1', 'Deadline 24h', 'Sensitive'],
        [
          'Voluntary recall demonstrates commitment to safety',
          'Fix is straightforward and available at all service centres',
          'No accidents reported related to this issue',
        ],
      ],
      [
        'InsideEVs',
        'Mark Thompson',
        'mthompson@insideevs.com',
        'journalist',
        'Cybertruck production hits 2,500/week milestone',
        'Positive piece on Cybertruck ramp. Requesting official production numbers and waitlist status.',
        'positive',
        'media_inquiry',
        5.0,
        6.5,
        2,
        4,
        [],
        [
          'Cybertruck demand continues to exceed production capacity',
          'Austin Gigafactory dedicated line running at increased efficiency',
        ],
      ],
      [
        'Financial Times',
        'Sarah Chen',
        'sarah.chen@ft.com',
        'journalist',
        'Cybertruck pricing analysis — margin pressure at $60k base',
        'FT investigating whether Cybertruck is profitable at current pricing. Analyst estimates suggest negative margins on base model.',
        'negative',
        'media_inquiry',
        7.5,
        8.5,
        5,
        7,
        ['Tier 1'],
        [
          'Tesla does not comment on product-level margins',
          'Cybertruck costs will improve with production scale',
        ],
      ],
      [
        'LA Times',
        'Maria Gonzalez',
        'mgonzalez@latimes.com',
        'journalist',
        'Cybertruck size complaints from urban residents',
        'Piece on Cybertruck dimensions causing issues in standard parking structures and residential streets in LA.',
        'negative',
        'media_inquiry',
        4.5,
        6.0,
        3,
        5,
        [],
        [
          'Cybertruck dimensions are comparable to other full-size trucks',
          'Steer-by-wire provides tighter turning radius than competitors',
        ],
      ],
      [
        'TechCrunch',
        'Alex Rivera',
        'alex.rivera@techcrunch.com',
        'freelancer',
        'Cybertruck accessories ecosystem — third party market booming',
        'Positive feature on aftermarket Cybertruck accessories. Requesting official Tesla stance on third-party modifications.',
        'positive',
        'media_inquiry',
        3.5,
        5.0,
        2,
        3,
        ['New Contact'],
        [
          'Tesla encourages responsible customisation',
          'Official accessories available through Tesla Shop',
        ],
      ],
    ],
  },
  {
    id: 'musk-political',
    title: 'Elon Musk — Political & DOGE Controversies',
    summary: "Musk's role in DOGE, political statements, and impact on Tesla brand perception.",
    priority: 'high',
    seeds: [
      [
        'Politico',
        'Kate Sullivan',
        'ksullivan@politico.com',
        'journalist',
        'Musk DOGE role drawing shareholder lawsuit threats',
        "Politico investigating potential shareholder derivative suits over Musk's time allocation to government role vs Tesla CEO duties.",
        'urgent',
        'media_inquiry',
        8.5,
        9.5,
        8,
        9,
        ['Tier 1', 'Sensitive', 'Deadline 24h'],
        [
          'Musk remains fully engaged as Tesla CEO',
          'Board of directors maintains appropriate governance oversight',
          'Cannot comment on potential litigation',
        ],
      ],
      [
        'New York Times',
        'Jennifer Walsh',
        'jwalsh@nytimes.com',
        'journalist',
        'Tesla boycott movement grows amid Musk political backlash',
        'NYT feature tracking organised boycott campaigns and their measurable impact on Tesla sales in blue states.',
        'negative',
        'media_inquiry',
        8.0,
        9.0,
        7,
        9,
        ['Tier 1', 'Sensitive'],
        [
          'Tesla focuses on building the best products for customers',
          'Q4 deliveries show continued strong demand globally',
        ],
      ],
      [
        'BBC',
        'Oliver Hughes',
        'oliver.hughes@bbc.co.uk',
        'journalist',
        'European backlash against Musk — Tesla sales down 40% in Germany',
        "BBC covering dramatic European sales decline linked to Musk's political activities. Requesting comment on regional strategy.",
        'negative',
        'media_inquiry',
        7.5,
        8.5,
        6,
        8,
        ['Tier 1'],
        [
          'European market remains core to Tesla strategy',
          'Berlin Gigafactory continues to expand production',
          'Multiple factors affect regional sales figures',
        ],
      ],
      [
        'Washington Post',
        'Amanda Cooper',
        'acooper@washpost.com',
        'journalist',
        'DOGE cost-cutting claims vs reality — fact-checking Musk',
        'WaPo fact-check on DOGE savings claims made by Musk. Requesting Tesla corporate response on CEO time allocation.',
        'negative',
        'media_inquiry',
        7.0,
        8.0,
        6,
        8,
        ['Tier 1', 'Sensitive'],
        [
          "Mr Musk's government advisory role is separate from Tesla operations",
          'Tesla executive team continues to execute on roadmap',
        ],
      ],
      [
        'Fortune',
        'Daniel Kim',
        'dkim@fortune.com',
        'journalist',
        'Tesla board independence questioned amid Musk controversies',
        'Feature on Tesla board governance. Examining whether board provides sufficient independent oversight of Musk.',
        'negative',
        'media_inquiry',
        6.5,
        7.5,
        5,
        7,
        [],
        [
          'Tesla board includes experienced independent directors',
          'Governance practices disclosed in annual proxy statement',
        ],
      ],
      [
        'MSNBC',
        'Rachel Adams',
        'radams@msnbc.com',
        'producer',
        'Panel discussion — should CEOs stay out of politics?',
        'Producer seeking Tesla spokesperson for panel on CEO political involvement. Other panellists include GM and Ford reps.',
        'neutral',
        'interview_request',
        5.0,
        6.5,
        5,
        7,
        ['Tier 1'],
        [
          'Decline — high-risk format with adversarial framing',
          'Suggest written statement instead',
        ],
      ],
      [
        'Electrek',
        'Fred Lambert',
        'fred@electrek.co',
        'editor',
        'Tesla owners distancing from brand — wrapping over logos',
        "Electrek covering trend of Tesla owners covering badges and logos to avoid association with Musk's politics.",
        'negative',
        'media_inquiry',
        5.5,
        7.0,
        4,
        6,
        [],
        [
          'Tesla vehicles speak for themselves through quality and innovation',
          'Customer satisfaction scores remain industry-leading',
        ],
      ],
    ],
  },
  {
    id: 'earnings-stock',
    title: 'Earnings, Stock & Valuation',
    summary: 'Quarterly earnings, analyst downgrades, market cap movements, and investor concerns.',
    priority: 'high',
    seeds: [
      [
        'Bloomberg',
        'Raj Patel',
        'rpatel@bloomberg.net',
        'journalist',
        'Tesla Q1 earnings preview — analysts expect margin squeeze',
        'Bloomberg pre-earnings piece. Consensus estimates show declining automotive margins for 5th consecutive quarter.',
        'neutral',
        'media_inquiry',
        7.5,
        8.5,
        5,
        7,
        ['Tier 1'],
        [
          'Tesla does not provide guidance on specific margins',
          'Focus on long-term growth and product roadmap',
        ],
      ],
      [
        'Wall Street Journal',
        'Michael Brooks',
        'mbrooks@wsj.com',
        'journalist',
        'Tesla valuation disconnect — $800B for a car company?',
        "WSJ feature questioning Tesla's valuation premium vs delivery growth slowdown. Requesting IR comment.",
        'negative',
        'media_inquiry',
        7.0,
        8.0,
        5,
        7,
        ['Tier 1'],
        [
          'Tesla is an energy and AI company, not just an automaker',
          'Robotaxi, energy storage, and Optimus represent massive TAM expansion',
        ],
      ],
      [
        'CNBC',
        'Brian Sullivan',
        'bsullivan@cnbc.com',
        'producer',
        'Tesla stock halving from peak — investor sentiment segment',
        'CNBC Closing Bell segment on Tesla stock decline. Requesting spokesperson for 5-min live interview.',
        'negative',
        'interview_request',
        7.0,
        8.0,
        6,
        8,
        ['Tier 1', 'Sensitive'],
        [
          'Stock price commentary outside our purview',
          'Focus on operational execution and product milestones',
        ],
      ],
      [
        'Financial Times',
        'Laura Martinez',
        'lmartinez@ft.com',
        'journalist',
        'Institutional investors quietly reducing Tesla positions',
        'FT tracking 13F filings showing major fund managers trimming Tesla holdings. Requesting comment.',
        'negative',
        'media_inquiry',
        6.5,
        7.5,
        4,
        6,
        ['Tier 1'],
        [
          'Tesla maintains strong institutional ownership',
          'Investment decisions are made by individual fund managers',
        ],
      ],
      [
        "Barron's",
        "Kevin O'Brien",
        'kobrien@barrons.com',
        'journalist',
        'Tesla energy business could justify standalone $200B valuation',
        'Positive analysis of Tesla Energy division growth. Requesting updated deployment figures for Megapack.',
        'positive',
        'media_inquiry',
        6.0,
        7.0,
        2,
        4,
        [],
        [
          'Energy storage deployments grew 200%+ year-over-year',
          'Lathrop Megafactory at full production capacity',
        ],
      ],
      [
        'Reuters',
        'Anna Schmidt',
        'aschmidt@reuters.com',
        'journalist',
        'Tesla delivery numbers Q1 — China registration data hints at miss',
        'Reuters using China insurance registration data to preview Q1 deliveries. Data suggests below-consensus figures.',
        'urgent',
        'media_inquiry',
        8.0,
        9.0,
        6,
        8,
        ['Tier 1', 'Deadline 24h'],
        [
          'Tesla reports official delivery numbers on scheduled dates',
          'Third-party estimates may not reflect complete picture',
        ],
      ],
    ],
  },
  {
    id: 'gigafactory-expansion',
    title: 'Gigafactory Expansion (Mexico, Austin, Berlin)',
    summary:
      'New factory plans, expansion permits, local government relations, and production scaling.',
    priority: 'medium',
    seeds: [
      [
        'Reuters',
        'Carlos Mendez',
        'cmendez@reuters.com',
        'journalist',
        'Tesla Mexico Gigafactory — construction restart signals go-ahead',
        'Reuters reporting signs of resumed construction at Monterrey site after year-long pause. Requesting confirmation.',
        'positive',
        'media_inquiry',
        6.5,
        7.5,
        3,
        5,
        ['Tier 1'],
        [
          'Tesla continues to evaluate global manufacturing capacity needs',
          'Mexico remains an important market for Tesla',
        ],
      ],
      [
        'Automotive News',
        'Rachel Foster',
        'rfoster@autonews.com',
        'editor',
        'Austin Gigafactory expansion permit filed — doubling capacity',
        "Trade pub covering Tesla's permit filing for major Austin expansion. Requesting timeline and production targets.",
        'positive',
        'media_inquiry',
        5.5,
        6.5,
        2,
        4,
        [],
        [
          "Austin Gigafactory is Tesla's US headquarters and manufacturing hub",
          'Expansion supports growing demand for Model Y and Cybertruck',
        ],
      ],
      [
        'Der Spiegel',
        'Hans Mueller',
        'hmueller@spiegel.de',
        'journalist',
        'Berlin Gigafactory water usage controversy resurfaces',
        'German outlet covering renewed environmental concerns about Grünheide factory water consumption and local protests.',
        'negative',
        'media_inquiry',
        6.0,
        7.5,
        5,
        7,
        ['Sensitive'],
        [
          'Berlin Gigafactory operates within all permitted water usage limits',
          'Tesla invested in water recycling systems exceeding regulatory requirements',
        ],
      ],
      [
        'Bloomberg',
        'Priya Sharma',
        'psharma@bloomberg.net',
        'journalist',
        'Tesla weighing India factory — Modi meeting follow-up',
        "Bloomberg tracking Tesla's India entry strategy after PM Modi meeting. Requesting update on market entry timeline.",
        'neutral',
        'media_inquiry',
        6.0,
        7.0,
        3,
        5,
        ['Tier 1'],
        [
          'Tesla continues to evaluate opportunities in India',
          'No specific announcements to share at this time',
        ],
      ],
      [
        'Nikkei Asia',
        'Yuki Tanaka',
        'y.tanaka@nikkei.com',
        'journalist',
        'Tesla Japan expansion — new delivery centres in Osaka and Fukuoka',
        'Nikkei covering Tesla retail expansion in Japan. Requesting comment on Japan market strategy.',
        'positive',
        'media_inquiry',
        5.0,
        6.0,
        2,
        3,
        [],
        [
          'Japan is a key market for Tesla',
          'New delivery centres improve customer experience and service access',
        ],
      ],
      [
        'Austin American-Statesman',
        'Jake Williams',
        'jwilliams@statesman.com',
        'journalist',
        'Tesla tax incentives — did Austin get a fair deal?',
        "Local paper examining Tesla's tax abatement deal for Gigafactory Texas. Requesting response to criticism.",
        'negative',
        'media_inquiry',
        4.5,
        6.0,
        4,
        6,
        [],
        [
          'Tesla has created over 20,000 jobs in Travis County',
          'Investment exceeds original commitments made to local government',
        ],
      ],
    ],
  },
  {
    id: 'labor-safety',
    title: 'Labor, Workplace Safety & Unionisation',
    summary:
      'OSHA complaints, union organising efforts, worker conditions, and safety record scrutiny.',
    priority: 'high',
    seeds: [
      [
        'New York Times',
        'Sarah Mitchell',
        'smitchell@nytimes.com',
        'journalist',
        'Tesla factory injury rates double industry average — OSHA data',
        'NYT analysis of OSHA data showing elevated injury rates at Fremont and Austin plants. Major investigative piece.',
        'urgent',
        'media_inquiry',
        8.5,
        9.5,
        8,
        9,
        ['Tier 1', 'Sensitive', 'Deadline 24h'],
        [
          "Worker safety is Tesla's top priority",
          'Injury rates have improved year-over-year',
          'Tesla invests heavily in ergonomic improvements and automation',
        ],
      ],
      [
        'Washington Post',
        'Tom Bradley',
        'tbradley@washpost.com',
        'journalist',
        'UAW targets Tesla — organising drive launches at Austin plant',
        "WaPo covering UAW's formal organising campaign at Gigafactory Texas. Requesting Tesla management response.",
        'negative',
        'media_inquiry',
        7.0,
        8.5,
        6,
        8,
        ['Tier 1', 'Sensitive'],
        [
          'Tesla employees receive industry-leading total compensation',
          'Workers have direct access to management and feedback channels',
        ],
      ],
      [
        'NPR',
        'Diana Ross',
        'dross@npr.org',
        'producer',
        'Working at Tesla — former employees speak out',
        'NPR producing segment featuring former Tesla workers describing conditions. Requesting current worker perspective.',
        'negative',
        'interview_request',
        6.5,
        7.5,
        6,
        8,
        ['Tier 1', 'Sensitive'],
        [
          'Suggest written statement rather than live interview',
          'Highlight employee benefits, stock grants, and career development',
        ],
      ],
      [
        'LA Times',
        'Carlos Ruiz',
        'cruiz@latimes.com',
        'journalist',
        'Temp workers at Tesla — two-tier workforce concerns',
        'Investigating use of contract workers at Fremont plant. Alleges different safety standards for temps vs direct hires.',
        'negative',
        'media_inquiry',
        6.0,
        7.5,
        5,
        7,
        ['Sensitive'],
        [
          'All workers at Tesla facilities receive same safety training and protections',
          'Tesla has reduced reliance on temporary workers over past two years',
        ],
      ],
      [
        'Bloomberg',
        'Hannah Lee',
        'hlee@bloomberg.net',
        'journalist',
        'Tesla whistleblower alleges safety data manipulation at Fremont',
        'Whistleblower claim that injury reports were suppressed. Bloomberg has internal documents. Requesting comment.',
        'urgent',
        'media_inquiry',
        9.0,
        9.5,
        8,
        9,
        ['Tier 1', 'Sensitive', 'VIP', 'Deadline 24h'],
        [
          'Tesla maintains rigorous safety reporting standards',
          'All allegations are thoroughly investigated',
          'Cannot comment on specific personnel matters',
        ],
      ],
      [
        'Electrek',
        'Fred Lambert',
        'fred@electrek.co',
        'editor',
        'Tesla raises factory worker pay — new minimum $22/hour',
        "Positive piece on Tesla's latest compensation increase for production workers. Requesting confirmation of numbers.",
        'positive',
        'media_inquiry',
        4.5,
        5.5,
        2,
        3,
        [],
        [
          'Tesla regularly reviews and adjusts compensation to remain competitive',
          'Total compensation includes stock grants, benefits, and career growth',
        ],
      ],
    ],
  },
  {
    id: 'energy-division',
    title: 'Energy Division — Megapack & Solar',
    summary:
      'Megapack deployments, utility-scale storage contracts, solar roof updates, and energy revenue growth.',
    priority: 'medium',
    seeds: [
      [
        'Financial Times',
        'Laura Martinez',
        'lmartinez@ft.com',
        'journalist',
        'Tesla Megapack wins largest US grid storage contract — 2GWh Texas project',
        'FT covering record-breaking utility storage deal. Requesting details on deployment timeline and financing.',
        'positive',
        'media_inquiry',
        6.5,
        7.5,
        2,
        4,
        ['Tier 1'],
        [
          'Tesla Energy is scaling rapidly to meet grid storage demand',
          'Lathrop and Shanghai Megafactories provide global supply',
        ],
      ],
      [
        'Bloomberg NEF',
        'James Morton',
        'jmorton@bnef.com',
        'journalist',
        'Tesla energy storage revenue to surpass auto by 2030 — analysis',
        "BloombergNEF modelling suggests energy could become Tesla's primary business. Requesting company perspective on energy strategy.",
        'positive',
        'media_inquiry',
        6.0,
        7.0,
        2,
        3,
        ['Tier 1'],
        [
          "Energy storage is a core pillar of Tesla's mission",
          'Management has highlighted energy as fastest-growing segment',
        ],
      ],
      [
        'Canary Media',
        'Rebecca Torres',
        'rtorres@canarymedia.com',
        'journalist',
        'Tesla Virtual Power Plant expanding to 5 new states',
        "Covering expansion of Tesla's Powerwall VPP programme using aggregated home batteries for grid services.",
        'positive',
        'media_inquiry',
        4.5,
        5.5,
        1,
        3,
        [],
        [
          'VPP demonstrates value of distributed energy resources',
          'Powerwall owners earn credits while supporting grid stability',
        ],
      ],
      [
        'CNBC',
        'Kevin Hart',
        'khart@cnbc.com',
        'producer',
        'Tesla solar roof — is it finally working?',
        'Segment examining Tesla Solar Roof after years of installation complaints. Requesting updated install numbers and customer satisfaction data.',
        'neutral',
        'interview_request',
        5.5,
        6.5,
        4,
        6,
        ['Tier 1'],
        [
          'Solar Roof installations have increased significantly',
          'Customer satisfaction improvements driven by better installation processes',
        ],
      ],
      [
        'Utility Dive',
        'Mark Peters',
        'mpeters@utilitydive.com',
        'editor',
        'Tesla Megapack supply constraints — utilities waiting 18 months',
        'Trade publication reporting long lead times for Megapack orders. Requesting comment on capacity expansion plans.',
        'neutral',
        'media_inquiry',
        5.0,
        6.0,
        3,
        5,
        [],
        [
          'Strong demand reflects market confidence in Tesla energy products',
          'Shanghai Megafactory adding significant new capacity',
        ],
      ],
      [
        'Reuters',
        'Anna Schmidt',
        'aschmidt@reuters.com',
        'journalist',
        'Tesla energy margins outpace automotive — earnings breakdown',
        'Reuters analysing segment profitability showing energy division with higher margins than car business.',
        'positive',
        'media_inquiry',
        6.0,
        7.0,
        3,
        4,
        ['Tier 1'],
        ['Tesla Energy benefits from manufacturing scale and vertical integration'],
      ],
      [
        'BBC',
        'Oliver Hughes',
        'oliver.hughes@bbc.co.uk',
        'journalist',
        "Australia's big battery — Tesla Megapack powering a state",
        'Documentary piece on large-scale Tesla battery installation in South Australia. Requesting interview with energy team.',
        'positive',
        'interview_request',
        5.5,
        6.5,
        1,
        3,
        ['Tier 1'],
        [
          'South Australia project demonstrates grid-scale battery viability',
          'Happy to arrange interview with energy deployment team',
        ],
      ],
    ],
  },
  {
    id: 'robotaxi',
    title: 'Robotaxi Programme',
    summary:
      'Autonomous ride-hailing plans, regulatory timeline, Cybercab unveil, and competition with Waymo.',
    priority: 'medium',
    seeds: [
      [
        'TechCrunch',
        'Jake Miller',
        'jmiller@techcrunch.com',
        'journalist',
        'Tesla robotaxi launch timeline slips again — Austin pilot delayed',
        "Reporting that Tesla's planned Austin robotaxi pilot has been pushed to H2 2026. Requesting updated timeline.",
        'negative',
        'media_inquiry',
        7.0,
        8.0,
        5,
        7,
        [],
        [
          'Tesla is committed to launching robotaxi service when safety standards are met',
          'Regulatory approvals are progressing in multiple jurisdictions',
        ],
      ],
      [
        'The Verge',
        'Sam Byford',
        'sbyford@theverge.com',
        'journalist',
        'Cybercab design vs Waymo Jaguar — form meets function',
        "Feature comparing Tesla Cybercab design philosophy with Waymo's approach. Requesting design team interview.",
        'neutral',
        'media_inquiry',
        5.0,
        6.5,
        2,
        4,
        ['New Contact'],
        [
          'Cybercab designed from ground up for autonomous operation',
          'No steering wheel or pedals reflects confidence in FSD capability',
        ],
      ],
      [
        'Bloomberg',
        'Emily Zhang',
        'ezhang@bloomberg.net',
        'journalist',
        'Tesla needs robotaxi to justify valuation — analyst consensus',
        "Bloomberg roundup of analyst notes tying Tesla's premium valuation to robotaxi delivery. Requesting management comment.",
        'neutral',
        'media_inquiry',
        6.5,
        7.5,
        4,
        6,
        ['Tier 1'],
        [
          'Robotaxi represents enormous addressable market',
          "Tesla's AI and manufacturing capabilities uniquely position for this opportunity",
        ],
      ],
      [
        'Ars Technica',
        'Tim Lee',
        'tlee@arstechnica.com',
        'journalist',
        'Can Tesla robotaxi work without lidar? Engineering analysis',
        'Technical deep-dive on vision-only approach for robotaxi. Requesting Tesla AI team perspective.',
        'neutral',
        'media_inquiry',
        5.0,
        6.0,
        3,
        5,
        [],
        [
          'Vision-based approach mirrors human driving',
          "Tesla's neural network training data advantage is unmatched",
        ],
      ],
      [
        'Politico',
        'Amanda Green',
        'agreen@politico.com',
        'journalist',
        'State-by-state robotaxi regulation — Tesla lobbying efforts',
        "Mapping Tesla's lobbying spend on autonomous vehicle legislation across US states.",
        'negative',
        'media_inquiry',
        6.0,
        7.5,
        5,
        7,
        ['Tier 1', 'Sensitive'],
        [
          'Tesla engages constructively with regulators to advance safe autonomous driving',
          'Transparent about advocacy for sensible AV regulation',
        ],
      ],
      [
        'Nikkei Asia',
        'Kenji Yamamoto',
        'kyamamoto@nikkei.com',
        'journalist',
        "Tesla robotaxi vs China's Baidu Apollo — race for autonomous rides",
        "Comparing Tesla and Baidu's robotaxi strategies in global markets.",
        'neutral',
        'media_inquiry',
        5.0,
        6.0,
        3,
        4,
        [],
        [
          "Tesla's global fleet provides unmatched real-world driving data",
          'Focus on scalable, cost-effective autonomy solution',
        ],
      ],
    ],
  },
  {
    id: 'model-y-refresh',
    title: 'Model Y Refresh & New Models',
    summary:
      'Juniper Model Y launch, next-gen platform, affordable model rumours, and product roadmap.',
    priority: 'medium',
    seeds: [
      [
        'Electrek',
        'Fred Lambert',
        'fred@electrek.co',
        'editor',
        'Model Y Juniper refresh — first reviews drop this week',
        'Electrek coordinating coverage of refreshed Model Y. Requesting press car for review and Tesla comment on changes.',
        'positive',
        'media_inquiry',
        6.0,
        7.0,
        2,
        4,
        [],
        [
          'Refreshed Model Y features significant interior and technology upgrades',
          'Happy to arrange press vehicle for review',
        ],
      ],
      [
        'Car and Driver',
        'Mike Collins',
        'mcollins@caranddriver.com',
        'editor',
        'Tesla sub-$30k model — when and what?',
        "Feature on Tesla's affordable vehicle plans. Musk's previous comments about $25k car. Requesting product roadmap clarity.",
        'neutral',
        'media_inquiry',
        6.5,
        7.5,
        4,
        6,
        [],
        [
          'Tesla is focused on making EVs accessible to more customers',
          'Cannot comment on unannounced products',
        ],
      ],
      [
        'Top Gear',
        'James Henderson',
        'jhenderson@topgear.com',
        'journalist',
        'New Roadster update — is it still happening?',
        'Checking in on long-delayed next-gen Roadster. Readers asking if project is cancelled.',
        'neutral',
        'media_inquiry',
        4.0,
        5.5,
        2,
        4,
        [],
        [
          "Roadster remains on Tesla's product roadmap",
          'Engineering team focused on delivering exceptional performance',
        ],
      ],
      [
        'Reuters',
        'Carlos Mendez',
        'cmendez@reuters.com',
        'journalist',
        'Tesla next-gen platform — $25k car in 2027?',
        'Reuters sources suggest new vehicle platform targets 2027 production start. Requesting confirmation.',
        'neutral',
        'media_inquiry',
        7.0,
        8.0,
        4,
        6,
        ['Tier 1'],
        [
          'Tesla continuously works on next-generation vehicle platforms',
          'Details will be shared at appropriate time',
        ],
      ],
      [
        'InsideEVs',
        'Mark Thompson',
        'mthompson@insideevs.com',
        'journalist',
        'Model Y Juniper vs BYD Seal U — spec comparison',
        'Comparison piece for EV shoppers. Requesting official spec sheet and pricing for refreshed Model Y.',
        'neutral',
        'media_inquiry',
        4.5,
        5.5,
        2,
        3,
        [],
        [
          'Full specifications available on tesla.com',
          'Model Y offers best-in-class range and technology',
        ],
      ],
      [
        'Motor Trend',
        'Angela Park',
        'apark@motortrend.com',
        'editor',
        'Tesla Model Y Juniper — Car of the Year contender?',
        'Motor Trend considering refreshed Model Y for annual award. Requesting long-term test vehicle.',
        'positive',
        'media_inquiry',
        5.5,
        6.5,
        1,
        3,
        [],
        [
          'Tesla appreciates consideration for this prestigious award',
          'Happy to provide extended review vehicle',
        ],
      ],
    ],
  },
  {
    id: 'china-competition',
    title: 'China Competition & BYD',
    summary:
      'BYD overtaking Tesla in sales, pricing wars, China market share erosion, and trade tensions.',
    priority: 'high',
    seeds: [
      [
        'Financial Times',
        'James Wilson',
        'jwilson@ft.com',
        'journalist',
        'BYD overtakes Tesla in global EV revenue for first time',
        'Major FT story on BYD surpassing Tesla in quarterly revenue. Requesting comment on competitive positioning.',
        'urgent',
        'media_inquiry',
        8.0,
        9.0,
        5,
        7,
        ['Tier 1', 'Deadline 24h'],
        [
          'Tesla competes on technology, safety, and total cost of ownership',
          'Growing EV market benefits all manufacturers',
        ],
      ],
      [
        'Bloomberg',
        'Emily Zhang',
        'ezhang@bloomberg.net',
        'journalist',
        'Tesla China price cuts — margin sacrifice for market share',
        "Tracking Tesla's third price reduction in China this year. Analysing impact on margins and competitor response.",
        'negative',
        'media_inquiry',
        7.0,
        8.0,
        5,
        7,
        ['Tier 1'],
        [
          'Pricing reflects manufacturing efficiencies and commitment to accessibility',
          "Shanghai Gigafactory is Tesla's most efficient production facility",
        ],
      ],
      [
        'South China Morning Post',
        'Li Wei',
        'lwei@scmp.com',
        'journalist',
        'Tesla data privacy concerns resurface in China — military base restrictions',
        'Covering renewed restrictions on Tesla vehicles near Chinese military installations due to camera concerns.',
        'negative',
        'media_inquiry',
        6.5,
        7.5,
        6,
        8,
        ['Sensitive'],
        [
          'Tesla vehicles do not transmit video data outside the vehicle',
          'All China user data stored on local servers per regulations',
        ],
      ],
      [
        'CNBC',
        'Lisa Nguyen',
        'lisa.nguyen@cnbc.com',
        'journalist',
        'China EV price war — Tesla caught between BYD and NIO',
        "Segment on intensifying price competition in Chinese EV market. Impact on Tesla's China strategy.",
        'neutral',
        'media_inquiry',
        6.0,
        7.0,
        4,
        6,
        ['Tier 1'],
        [
          'Tesla offers compelling value across all price segments',
          'Focus on total ownership experience, not just sticker price',
        ],
      ],
      [
        'Nikkei Asia',
        'Yuki Tanaka',
        'y.tanaka@nikkei.com',
        'journalist',
        'BYD vs Tesla in Southeast Asia — new battleground',
        'Covering competition for EV dominance in Thailand, Indonesia, and Vietnam.',
        'neutral',
        'media_inquiry',
        5.5,
        6.5,
        3,
        5,
        [],
        [
          'Tesla continues to expand presence in Southeast Asian markets',
          'Supercharger network is key differentiator in emerging markets',
        ],
      ],
      [
        'Wall Street Journal',
        'Peter Chang',
        'pchang@wsj.com',
        'journalist',
        'US tariffs on Chinese EVs — does Tesla benefit or lose?',
        "Analysing impact of proposed tariff increases on Tesla's competitive position vs Chinese imports.",
        'neutral',
        'media_inquiry',
        7.0,
        8.0,
        4,
        6,
        ['Tier 1'],
        [
          'Tesla supports policies that accelerate sustainable energy transition',
          'Majority of Tesla vehicles sold in US are manufactured domestically',
        ],
      ],
    ],
  },
  {
    id: 'supercharger-nacs',
    title: 'Supercharger Network & NACS',
    summary:
      'NACS adoption by other automakers, Supercharger expansion, and charging network as competitive moat.',
    priority: 'low',
    seeds: [
      [
        'Electrek',
        'Fred Lambert',
        'fred@electrek.co',
        'editor',
        'Ford and GM drivers now using Tesla Superchargers — early reports',
        'Covering first-month experience of non-Tesla EVs on Supercharger network. Requesting reliability data.',
        'positive',
        'media_inquiry',
        5.0,
        6.0,
        2,
        3,
        [],
        [
          'Tesla welcomes all EV drivers to the Supercharger network',
          'Network reliability remains above 99.9%',
        ],
      ],
      [
        'The Verge',
        'Sean Hollister',
        'shollister@theverge.com',
        'journalist',
        'Tesla Supercharger expansion back on track after layoffs',
        'Follow-up on Supercharger team rebuilding after mass layoffs. New stations opening at accelerated pace.',
        'positive',
        'media_inquiry',
        5.5,
        6.5,
        3,
        5,
        [],
        [
          'Tesla continues to invest heavily in charging infrastructure',
          'Thousands of new Supercharger stalls planned for 2026',
        ],
      ],
      [
        'Automotive News',
        'Rachel Foster',
        'rfoster@autonews.com',
        'editor',
        'NACS becomes de facto US charging standard — implications',
        'Trade piece on NACS replacing CCS as industry standard. Requesting Tesla comment on licensing terms.',
        'positive',
        'media_inquiry',
        5.0,
        6.0,
        2,
        3,
        [],
        ['NACS adoption benefits all EV drivers', 'Tesla made NACS available as open standard'],
      ],
      [
        'Reuters',
        'James Morrison',
        'james.morrison@reuters.com',
        'journalist',
        'Tesla Supercharger revenue could hit $5B by 2028 — analysis',
        'Reuters modelling Supercharger revenue with NACS adoption. Requesting comment on charging business model.',
        'positive',
        'media_inquiry',
        6.0,
        7.0,
        2,
        4,
        ['Tier 1'],
        [
          'Supercharger network is critical infrastructure for EV adoption',
          'Revenue details reported in quarterly earnings',
        ],
      ],
      [
        'Ars Technica',
        'Jonathan Gitlin',
        'jgitlin@arstechnica.com',
        'journalist',
        'Tesla Magic Dock rollout status — CCS adapter availability',
        'Tracking Magic Dock deployment progress at Supercharger locations for CCS-equipped vehicles.',
        'neutral',
        'media_inquiry',
        4.0,
        5.0,
        1,
        3,
        [],
        [
          'Magic Dock rollout continues across the network',
          'Goal is universal access for all EV drivers',
        ],
      ],
      [
        'InsideEVs',
        'Patrick George',
        'pgeorge@insideevs.com',
        'journalist',
        'Supercharger V4 — faster charging and pull-through design',
        'Preview of next-gen Supercharger hardware. Requesting technical specs and rollout timeline.',
        'positive',
        'media_inquiry',
        4.5,
        5.5,
        1,
        3,
        [],
        [
          'V4 Superchargers deliver faster charging for all vehicles',
          'Pull-through design accommodates vehicles with trailers',
        ],
      ],
    ],
  },
  {
    id: 'brand-reputation',
    title: 'Brand Reputation & Consumer Sentiment',
    summary:
      'Brand tracking surveys, customer satisfaction shifts, social media sentiment, and PR crisis management.',
    priority: 'high',
    seeds: [
      [
        'New York Times',
        'Jennifer Walsh',
        'jwalsh@nytimes.com',
        'journalist',
        'Tesla brand perception hits all-time low — Morning Consult data',
        'NYT citing brand tracking data showing Tesla favourability dropping across demographics. Feature piece.',
        'negative',
        'media_inquiry',
        8.0,
        9.0,
        7,
        9,
        ['Tier 1', 'Sensitive'],
        [
          "Tesla's products continue to earn highest customer satisfaction in the industry",
          'Brand perception surveys capture one data point; purchase intent and loyalty tell the full story',
        ],
      ],
      [
        'Ad Age',
        'Kim Larson',
        'klarson@adage.com',
        'journalist',
        "Tesla's $0 ad spend strategy — is it still working?",
        "Marketing trade pub examining Tesla's advertising approach now that they've started running some ads.",
        'neutral',
        'media_inquiry',
        4.5,
        5.5,
        2,
        4,
        [],
        [
          'Tesla lets its products and customers be its best advocates',
          'Recent advertising helps educate consumers about EV benefits',
        ],
      ],
      [
        'BBC',
        'Sophie Turner',
        'sturner@bbc.co.uk',
        'producer',
        'The Tesla effect — how one brand shaped the EV revolution',
        "Documentary series on Tesla's influence on the global auto industry. 3-part series for BBC Two.",
        'positive',
        'interview_request',
        6.0,
        7.0,
        2,
        4,
        ['Tier 1'],
        [
          'Compelling storytelling opportunity',
          'Request detailed treatment and editorial controls',
        ],
      ],
      [
        'Axios',
        'Dan Primack',
        'dprimack@axios.com',
        'journalist',
        'Tesla customer loyalty dropping — trade-in data shows shift to Rivian, BMW',
        'Citing auto data providers showing increased Tesla trade-ins for competitor EVs. Requesting response.',
        'negative',
        'media_inquiry',
        7.0,
        8.0,
        5,
        7,
        [],
        [
          'Tesla has highest repeat purchase rate in auto industry',
          'Overall customer satisfaction remains industry-leading',
        ],
      ],
      [
        'Washington Post',
        'Amanda Cooper',
        'acooper@washpost.com',
        'journalist',
        'Vandalised Teslas — hate crimes or political protest?',
        'Covering increase in Tesla vehicle vandalism linked to political backlash. Requesting Tesla statement.',
        'urgent',
        'media_inquiry',
        7.5,
        8.5,
        7,
        9,
        ['Tier 1', 'Sensitive'],
        [
          'Tesla condemns vandalism in all forms',
          'Sentry Mode provides evidence for law enforcement',
          'Vehicle owners should not be targeted for their choice of car',
        ],
      ],
      [
        'Wired',
        'Aarian Marshall',
        'amarshall@wired.com',
        'journalist',
        'Gen Z and Tesla — brand appeal fading with young buyers',
        'Feature on generational shift in Tesla brand perception. Survey data shows declining interest among under-30s.',
        'negative',
        'media_inquiry',
        5.5,
        6.5,
        4,
        6,
        [],
        [
          'Tesla continues to attract diverse new customers',
          'Model 3 and Model Y remain top-selling EVs globally',
        ],
      ],
      [
        'Forbes',
        'Alan Ohnsman',
        'aohnsman@forbes.com',
        'journalist',
        "Tesla's PR problem — the cost of having no comms team",
        "Examining Tesla's decision to not have a traditional PR department and its impact on brand management.",
        'negative',
        'media_inquiry',
        5.0,
        6.5,
        3,
        5,
        [],
        [
          'Tesla communicates directly with customers and stakeholders',
          'This approach ensures authenticity and speed',
        ],
      ],
    ],
  },
];
