import type { UserProfile } from '@/hooks/useAuth';
import type { Project } from '@/hooks/useProject';
import type { TriageRow } from '@/hooks/useTriageRealtime';

export const DEMO_TEAM = [
  { id: 'demo-user-001', name: 'Richard Appleton', email: 'richard@milltownpartners.com' },
  { id: 'demo-user-002', name: 'Sophie Martinez', email: 'sophie@milltownpartners.com' },
  { id: 'demo-user-003', name: 'James Chen', email: 'james@milltownpartners.com' },
];

export interface DemoStory {
  id: string;
  title: string;
  summary: string;
  owner_id: string | null;
  owner_name: string | null;
  triage_ids: string[];
  priority: 'high' | 'medium' | 'low';
}

export const DEMO_STORIES: DemoStory[] = [
  {
    id: 's1',
    title: 'FAA Certification & Regulatory Scrutiny',
    summary: 'Multiple outlets probing certification timeline, lobbying, and technical readiness.',
    owner_id: 'demo-user-001',
    owner_name: 'Richard Appleton',
    triage_ids: ['t1', 't14', 't15', 't5'],
    priority: 'high',
  },
  {
    id: 's2',
    title: 'Funding & Valuation Pressure',
    summary:
      'Series F rumours driving financial media interest. Market-sensitive — legal review required.',
    owner_id: null,
    owner_name: null,
    triage_ids: ['t6', 't9', 't10'],
    priority: 'high',
  },
  {
    id: 's3',
    title: 'Community Noise Concerns',
    summary: 'Noise complaints near test facilities gaining traction. Reuters publishing tomorrow.',
    owner_id: 'demo-user-002',
    owner_name: 'Sophie Martinez',
    triage_ids: ['t2', 't11', 't3'],
    priority: 'high',
  },
  {
    id: 's4',
    title: 'Product & Operations',
    summary: 'Positive coverage opportunities — test programme, workforce, Japan expansion.',
    owner_id: 'demo-user-003',
    owner_name: 'James Chen',
    triage_ids: ['t8', 't12', 't13'],
    priority: 'medium',
  },
];

export const DEMO_USER: UserProfile = {
  id: 'demo-user-001',
  email: 'richard@milltownpartners.com',
  name: 'Richard Appleton',
  role: 'admin',
  org_id: 'demo-org-001',
  slack_user_id: null,
};

export const DEMO_PROJECT: Project = {
  id: 'demo-project-001',
  name: 'Joby Aviation',
  slug: 'joby-aviation',
  status: 'active',
  receiving_address: 'joby@filter.milltownpartners.com',
  slack_channel_id: null,
  created_at: '2026-03-01T00:00:00Z',
};

export const DEMO_TRIAGE: TriageRow[] = [
  {
    id: 't1',
    email_id: 'e1',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Financial Times',
    sentiment: 'neutral',
    summary:
      "Requesting comment on Joby Aviation's FAA certification progress for a feature on the future of urban air mobility. Deadline Friday 5pm GMT.",
    composite_score: 8.7,
    impact_score: 9,
    urgency_score: 8,
    risk_score: 4,
    recommended_action: 'respond_today',
    flags: ['Tier 1', 'Deadline 24h'],
    status: 'new',
    assigned_to: null,
    reasoning:
      'Tier 1 outlet with significant readership among investors and regulators. Active deadline creates urgency. Low risk — straightforward progress inquiry with no adversarial angle.',
    talking_points: [
      'FAA certification on track for timeline shared at last earnings call',
      'Recent successful test flights in Marina, CA demonstrate operational readiness',
      'Offer spokesperson availability for follow-up questions',
    ],
    draft_reply_subject: 'Re: Comment request — Joby Aviation FAA certification',
    draft_reply_body:
      "Dear Sarah,\n\nThank you for reaching out. We'd be happy to provide comment for your feature.\n\nJoby's FAA certification programme continues to progress well, with recent milestones including [specific milestone]. We remain on track for the timeline we've previously communicated.\n\nWould you be available for a brief call with our Head of Communications this week? We could arrange something ahead of your Friday deadline.\n\nBest regards",
    draft_reply_tone: 'professional, cooperative',
    draft_reply_requires_approval: false,
    created_at: '2026-03-21T14:30:00Z',
    updated_at: '2026-03-21T14:31:00Z',
    emails: {
      subject: 'Comment request — upcoming feature on urban air mobility',
      from_name: 'Sarah Chen',
      from_address: 'sarah.chen@ft.com',
      received_at: '2026-03-21T14:28:00Z',
    },
  },
  {
    id: 't2',
    email_id: 'e2',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Reuters',
    sentiment: 'urgent',
    summary:
      "Reuters investigating allegations of noise complaints from residents near Joby's test facility. Publishing tomorrow. Requesting response by 6pm today.",
    composite_score: 9.2,
    impact_score: 10,
    urgency_score: 9,
    risk_score: 8,
    recommended_action: 'respond_immediately',
    flags: ['Tier 1', 'Deadline 24h', 'Sensitive', 'VIP'],
    status: 'new',
    assigned_to: null,
    reasoning:
      'Wire service with global distribution. Adversarial angle on noise complaints could impact regulatory narrative and community relations. Immediate response needed to shape coverage.',
    talking_points: [
      'Joby aircraft are among the quietest eVTOL designs — 100x quieter than conventional helicopters during flyover',
      'Community engagement programme active since 2025',
      'All testing conducted within FAA-approved hours and noise limits',
    ],
    draft_reply_subject: 'Re: Joby Aviation — noise complaint allegations',
    draft_reply_body:
      "Thank you for reaching out ahead of publication. We take community feedback seriously.\n\nJoby's aircraft are designed to be exceptionally quiet — producing noise levels comparable to a typical conversation during flyover, which is approximately 100 times quieter than a conventional helicopter.\n\nWe have maintained an active community engagement programme since 2025 and all testing operations are conducted within FAA-approved parameters.\n\nWe would welcome the opportunity to provide additional technical detail and connect you with our community liaison. Could we arrange a call this afternoon?",
    draft_reply_tone: 'measured, factual, non-defensive',
    draft_reply_requires_approval: true,
    draft_reply_approval_reason:
      'Touches sensitive topic — community relations and regulatory compliance',
    created_at: '2026-03-21T15:00:00Z',
    updated_at: '2026-03-21T15:01:00Z',
    emails: {
      subject: 'URGENT: Joby Aviation noise complaints — response needed by 6pm',
      from_name: 'James Morrison',
      from_address: 'james.morrison@reuters.com',
      received_at: '2026-03-21T14:55:00Z',
    },
  },
  {
    id: 't3',
    email_id: 'e3',
    project_id: 'demo-project-001',
    category: 'interview_request',
    sender_type: 'producer',
    outlet_name: 'BBC World Service',
    sentiment: 'positive',
    summary:
      'Producing a segment on sustainable aviation for BBC World Service radio. Requesting 15-minute interview with CEO or CTO for next week.',
    composite_score: 7.1,
    impact_score: 8,
    urgency_score: 5,
    risk_score: 3,
    recommended_action: 'respond_today',
    flags: ['Tier 1'],
    status: 'in_progress',
    assigned_to: 'demo-user-001',
    reasoning:
      'BBC World Service has massive global reach. Positive framing on sustainability aligns with company messaging. Flexible timeline allows proper spokesperson prep.',
    talking_points: [
      "Joby's all-electric aircraft produce zero operating emissions",
      'Partnership with Delta Air Lines for airport-to-city routes',
      'CEO availability for interview next Tuesday or Wednesday',
    ],
    draft_reply_subject: 'Re: BBC World Service — sustainable aviation segment',
    draft_reply_body:
      "Dear Priya,\n\nThank you for considering Joby Aviation for your segment — we'd be delighted to participate.\n\nOur CEO would be available for a 15-minute interview on either Tuesday or Wednesday next week. Could you share a brief outline of the topics you'd like to cover so we can ensure the most productive conversation?\n\nLooking forward to it.",
    draft_reply_tone: 'warm, enthusiastic',
    draft_reply_requires_approval: false,
    created_at: '2026-03-21T10:00:00Z',
    updated_at: '2026-03-21T11:00:00Z',
    emails: {
      subject: 'BBC World Service — sustainable aviation interview request',
      from_name: 'Priya Sharma',
      from_address: 'priya.sharma@bbc.co.uk',
      received_at: '2026-03-21T09:45:00Z',
    },
  },
  {
    id: 't4',
    email_id: 'e4',
    project_id: 'demo-project-001',
    category: 'event_invitation',
    sender_type: 'pr_agency',
    outlet_name: null,
    sentiment: 'neutral',
    summary:
      'Invitation to speak at the Future of Flight Summit in San Francisco, April 15-16. Panel on eVTOL commercialisation.',
    composite_score: 4.8,
    impact_score: 5,
    urgency_score: 3,
    risk_score: 2,
    recommended_action: 'respond_this_week',
    flags: [],
    status: 'new',
    assigned_to: null,
    reasoning:
      'Industry event with moderate visibility. Good thought leadership opportunity but no time pressure.',
    talking_points: [],
    created_at: '2026-03-20T16:00:00Z',
    updated_at: '2026-03-20T16:01:00Z',
    emails: {
      subject: 'Speaking invitation — Future of Flight Summit, April 15-16',
      from_name: 'Michael Torres',
      from_address: 'mtorres@aviationevents.com',
      received_at: '2026-03-20T15:50:00Z',
    },
  },
  {
    id: 't5',
    email_id: 'e5',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'freelancer',
    outlet_name: 'TechCrunch',
    sentiment: 'neutral',
    summary:
      "Freelancer writing a piece for TechCrunch comparing eVTOL companies' approaches to battery technology. Requesting technical details.",
    composite_score: 5.9,
    impact_score: 6,
    urgency_score: 5,
    risk_score: 4,
    recommended_action: 'respond_this_week',
    flags: ['New Contact'],
    status: 'new',
    assigned_to: null,
    reasoning:
      'TechCrunch reaches key tech/investor audience. Competitive comparison piece requires careful messaging to avoid giving away proprietary details.',
    talking_points: [
      "Highlight Joby's vertical integration approach to battery and powertrain",
      'Reference publicly disclosed range and performance specs only',
      'Do not discuss specific cell chemistry or supplier relationships',
    ],
    created_at: '2026-03-21T08:00:00Z',
    updated_at: '2026-03-21T08:01:00Z',
    emails: {
      subject: 'eVTOL battery tech comparison — request for comment',
      from_name: 'Alex Rivera',
      from_address: 'alex.rivera.writes@gmail.com',
      received_at: '2026-03-21T07:45:00Z',
    },
  },
  {
    id: 't6',
    email_id: 'e6',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Wall Street Journal',
    sentiment: 'neutral',
    summary:
      'Requesting comment on rumoured Series F funding round. Sources suggest $500M raise at $8B valuation.',
    composite_score: 8.4,
    impact_score: 9,
    urgency_score: 7,
    risk_score: 8,
    recommended_action: 'respond_immediately',
    flags: ['Tier 1', 'Sensitive', 'VIP'],
    status: 'new',
    assigned_to: null,
    reasoning:
      'WSJ covers markets closely — story will move stock sentiment. Funding details are market-sensitive. Response must be legally reviewed.',
    talking_points: [
      'Standard response: company does not comment on market speculation',
      'If pressed, refer to most recent public financial disclosures',
    ],
    draft_reply_subject: 'Re: Joby Aviation funding inquiry',
    draft_reply_body:
      "Thank you for reaching out. As a matter of policy, Joby Aviation does not comment on market speculation or rumoured financial transactions.\n\nFor the most up-to-date financial information, I'd direct you to our recent public filings and investor materials.\n\nPlease don't hesitate to reach out on other matters.",
    draft_reply_tone: 'professional, brief, non-committal',
    draft_reply_requires_approval: true,
    draft_reply_approval_reason: 'Market-sensitive financial information',
    created_at: '2026-03-21T13:00:00Z',
    updated_at: '2026-03-21T13:01:00Z',
    emails: {
      subject: 'Joby Aviation — Series F funding enquiry',
      from_name: 'David Park',
      from_address: 'david.park@wsj.com',
      received_at: '2026-03-21T12:48:00Z',
    },
  },
  {
    id: 't7',
    email_id: 'e7',
    project_id: 'demo-project-001',
    category: 'pr_agency_pitch',
    sender_type: 'pr_agency',
    outlet_name: null,
    sentiment: 'neutral',
    summary: 'PR agency pitching their aviation sector services. Mass email template.',
    composite_score: 1.4,
    impact_score: 1,
    urgency_score: 1,
    risk_score: 1,
    recommended_action: 'no_action',
    flags: [],
    status: 'no_action',
    assigned_to: null,
    created_at: '2026-03-19T09:00:00Z',
    updated_at: '2026-03-19T09:01:00Z',
    emails: {
      subject: 'Elevate your aviation PR with SkyComms Agency',
      from_name: 'SkyComms Team',
      from_address: 'hello@skycomms.io',
      received_at: '2026-03-19T08:30:00Z',
    },
  },
  {
    id: 't8',
    email_id: 'e8',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'editor',
    outlet_name: 'The Verge',
    sentiment: 'positive',
    summary:
      "Editor commissioning a long-form profile of Joby's test pilot programme. Requesting access for a ride-along at the Marina facility.",
    composite_score: 7.5,
    impact_score: 7,
    urgency_score: 4,
    risk_score: 6,
    recommended_action: 'schedule_briefing',
    flags: ['New Contact'],
    status: 'new',
    assigned_to: null,
    reasoning:
      'The Verge reaches influential tech audience. Profile piece is high-value for brand awareness. Facility access requires security review and legal clearance.',
    talking_points: [
      'Positive opportunity for in-depth brand storytelling',
      'Facility access requires NDA and security clearance — 2 week lead time',
      'Propose initial call to scope the piece before committing to access',
    ],
    created_at: '2026-03-21T11:00:00Z',
    updated_at: '2026-03-21T11:01:00Z',
    emails: {
      subject: 'The Verge — Joby test pilot programme profile',
      from_name: 'Elena Vasquez',
      from_address: 'elena@theverge.com',
      received_at: '2026-03-21T10:30:00Z',
    },
  },
  {
    id: 't9',
    email_id: 'e9',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Bloomberg',
    sentiment: 'neutral',
    summary:
      'Investigating SPAC valuation concerns ahead of Q1 earnings. Requesting comment on investor sentiment.',
    composite_score: 7.8,
    impact_score: 8,
    urgency_score: 7,
    risk_score: 7,
    recommended_action: 'respond_today',
    flags: ['Tier 1', 'Sensitive'],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-21T09:00:00Z',
    updated_at: '2026-03-21T09:01:00Z',
    emails: {
      subject: 'SPAC valuation concerns ahead of Q1',
      from_name: 'Raj Patel',
      from_address: 'rpatel@bloomberg.net',
      received_at: '2026-03-21T08:45:00Z',
    },
  },
  {
    id: 't10',
    email_id: 'e10',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'CNBC',
    sentiment: 'neutral',
    summary:
      'Producing a segment comparing eVTOL stock performance across public companies. Requesting data and spokesperson.',
    composite_score: 6.3,
    impact_score: 7,
    urgency_score: 5,
    risk_score: 5,
    recommended_action: 'respond_this_week',
    flags: ['Tier 1'],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-21T07:30:00Z',
    updated_at: '2026-03-21T07:31:00Z',
    emails: {
      subject: 'eVTOL stock performance comparison',
      from_name: 'Lisa Nguyen',
      from_address: 'lisa.nguyen@cnbc.com',
      received_at: '2026-03-21T07:15:00Z',
    },
  },
  {
    id: 't11',
    email_id: 'e11',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'LA Times',
    sentiment: 'negative',
    summary:
      'Residents near Marina del Rey test site seeking noise restrictions. Local council vote next week.',
    composite_score: 7.9,
    impact_score: 8,
    urgency_score: 8,
    risk_score: 7,
    recommended_action: 'respond_today',
    flags: ['Sensitive', 'Deadline 24h'],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-21T12:00:00Z',
    updated_at: '2026-03-21T12:01:00Z',
    emails: {
      subject: 'Residents seek noise restrictions near test site',
      from_name: 'Maria Gonzalez',
      from_address: 'mgonzalez@latimes.com',
      received_at: '2026-03-21T11:45:00Z',
    },
  },
  {
    id: 't12',
    email_id: 'e12',
    project_id: 'demo-project-001',
    category: 'interview_request',
    sender_type: 'journalist',
    outlet_name: 'Fast Company',
    sentiment: 'positive',
    summary:
      'Feature on eVTOL pilot training and workforce development. Seeking interview with head of operations.',
    composite_score: 6.8,
    impact_score: 7,
    urgency_score: 5,
    risk_score: 3,
    recommended_action: 'respond_this_week',
    flags: [],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-20T14:00:00Z',
    updated_at: '2026-03-20T14:01:00Z',
    emails: {
      subject: 'eVTOL pilot training & workforce development',
      from_name: 'Tom Bradley',
      from_address: 'tbradley@fastcompany.com',
      received_at: '2026-03-20T13:45:00Z',
    },
  },
  {
    id: 't13',
    email_id: 'e13',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Nikkei Asia',
    sentiment: 'positive',
    summary:
      'Covering Japan market entry and ANA partnership. Requesting comment on Asia-Pacific expansion plans.',
    composite_score: 6.5,
    impact_score: 7,
    urgency_score: 4,
    risk_score: 3,
    recommended_action: 'respond_this_week',
    flags: [],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-20T06:00:00Z',
    updated_at: '2026-03-20T06:01:00Z',
    emails: {
      subject: 'Japan market entry — ANA partnership',
      from_name: 'Yuki Tanaka',
      from_address: 'y.tanaka@nikkei.com',
      received_at: '2026-03-20T05:30:00Z',
    },
  },
  {
    id: 't14',
    email_id: 'e14',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Politico',
    sentiment: 'urgent',
    summary:
      'Investigating FAA rulemaking process and eVTOL lobbying spend. FOIA documents referenced.',
    composite_score: 8.1,
    impact_score: 9,
    urgency_score: 8,
    risk_score: 8,
    recommended_action: 'respond_immediately',
    flags: ['Tier 1', 'Sensitive', 'Deadline 24h'],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-21T16:00:00Z',
    updated_at: '2026-03-21T16:01:00Z',
    emails: {
      subject: 'FAA rulemaking & lobbying spend — comment request',
      from_name: 'Kate Sullivan',
      from_address: 'ksullivan@politico.com',
      received_at: '2026-03-21T15:45:00Z',
    },
  },
  {
    id: 't15',
    email_id: 'e15',
    project_id: 'demo-project-001',
    category: 'media_inquiry',
    sender_type: 'journalist',
    outlet_name: 'Aviation Week',
    sentiment: 'neutral',
    summary:
      'Annual type certificate timeline update for 2026 industry forecast. Non-urgent but important for trade audience.',
    composite_score: 7.0,
    impact_score: 7,
    urgency_score: 4,
    risk_score: 4,
    recommended_action: 'respond_this_week',
    flags: [],
    status: 'new',
    assigned_to: null,
    created_at: '2026-03-20T11:00:00Z',
    updated_at: '2026-03-20T11:01:00Z',
    emails: {
      subject: 'Type certificate timeline update 2026',
      from_name: 'Mark Davies',
      from_address: 'mdavies@aviationweek.com',
      received_at: '2026-03-20T10:30:00Z',
    },
  },
];
